name: Run bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Setup deps
        run: yarn
      - name: Setup creds path
        run: mkdir secrets
      - name: Setup creds
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.SHEETS_API_FILE }}
          dir: 'secrets/'
      - name: Get old players-new
        uses: actions/download-artifact@master
        with:
          name: new-players
          path: cron/data/players-new.json
      - name: Get old timestamp
        uses: actions/download-artifact@master
        with:
          name: timestamp
          path: cron/data/timestamp.json
      - name: Run thing
        run: bash cron/run.sh
      - name: Upload data
        uses: actions/upload-artifact@master
        with:
          name: new-players
          path: cron/data/players-new.json
      - name: Upload timestamp
        uses: actions/upload-artifact@master
        with:
          name: timestamp
          path: cron/data/timestamp.json
      - name: Deploy
        run: npm run deploy
