name: Run bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Set up secret
        run: |
          mkdir secrets
          echo "${{ secrets.GOOGLE }}" > secrets/creds.json
      - name: Run thing
        run: bash cron/run.sh
