name: Run bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Setup deps
        run: yarn
      - name: Setup folders
        run: |
          mkdir secrets
          mkdir cron/data
      - name: Setup creds
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "creds.json"
          json: ${{ secrets.SHEETS_API_FILE }}
          dir: 'secrets/'
      - name: Get old players-new
        uses: dawidd6/action-download-artifact@v2
        with:
          name: players-new.json
          path: cron/data/
          if_no_artifact_found: ignore
      - name: Faje
        run: touch cron/data/players-new.json
      - name: Get old timestamp
        uses: dawidd6/action-download-artifact@v2
        with:
          name: timestamp.json
          path: cron/data/
          if_no_artifact_found: ignore
      - name: Run thing
        run: bash cron/run.sh
      - name: Upload data
        uses: actions/upload-artifact@master
        with:
          name: players-new.json
          path: cron/data/
      - name: Upload timestamp
        uses: actions/upload-artifact@master
        with:
          name: timestamp.json
          path: cron/data/
      - name: Deploy
        run: npm run deploy
